### ISSUE TITLE
Automatically publish microsite via travis

### ISSUE THREAD

**Issue by amohrland** [Banno/kafka4s#20]
Docs: https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html#publish-using-github4s

**Comment by zcox** [comment]
I added the `GITHUB_TOKEN` env var to travis-ci, and the `sbt docs/publishMicrosite` command at the end of the build no longer fails, but I haven't made any microsite changes to actually publish yet.

**Comment by amohrland** [comment]
#21 updates docs and would test this out.

**Comment by amohrland** [comment]
Looks like the token worked! 🎉The doc updates in #21 were automatically published after merging.
