### ISSUE TITLE
Remove Stream constructors?

### ISSUE THREAD

**Issue by zcox** [Banno/kafka4s#47]
Should we remove the `ConsumerApi` and `ProducerApi` constructors that return `Stream`? Now that we have `Resource` to close things properly, and `Stream.resource`, they don't provide much value, and it's not clear in the type that they are singleton streams.

Their only real value appears to be typing fewer chars: `ConsumerApi.stream...` instead of `Stream.resource(ConsumerApi.resource...)`.

**Comment by calvinbrown085** [comment]
+1 to this.

**Comment by calvinbrown085** [comment]
Would the action on this ticket be something like removing https://github.com/Banno/kafka4s/blob/master/core/src/main/scala/com/banno/kafka/consumer/ConsumerApi.scala#L137 this constructor in favor of just using the `.resource` constructor?

**Comment by zcox** [comment]
@calvinbrown085 yep removing all of those `stream` functions, and then updating `examples` and `docs` probably to just use `Stream.resource`.

**Comment by calvinbrown085** [comment]
I'd say that'd be good, a lot of the newer apps i've experience can just `Stream.resource` if you need it, i'm not sure there's much benefit to providing it in the `ConsumerApi` methods. IMO.

**Comment by calvinbrown085** [comment]
I'd be happy to work on this if that's cool

**Comment by amohrland** [comment]
@calvinbrown085 Awesome, thanks 👍 

I agree with you guys that `Resource` better communicates that it's _a single_ resource and that removing the `stream`s removes a potential source of ambiguity.

**Comment by calvinbrown085** [comment]
What do we want to do here? https://github.com/Banno/kafka4s/blob/master/examples/src/main/scala/example3/ExampleApp.scala#L57

It looks like we are merging these two streams, AFAIK there's no way to merge resources. Do we want to just `Stream.resource` here?

**Comment by zcox** [comment]
@calvinbrown085 yeah I would replace `ConsumerApi.stream(...)` with `Stream.resource(ConsumerApi.resource(...))` and same with producer above.

**Comment by calvinbrown085** [comment]
@zcox Yep, that makes the most sense to me.

**Comment by calvinbrown085** [comment]
@zcox I'm closing this issue.
