### ISSUE TITLE
Solve, or document, the problem with javax.ws.rs-api

### ISSUE THREAD

**Issue by zcox** [Banno/kafka4s#60]
New users have repeatedly reported this problem in sbt when first getting started with kafka4s:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: javax.ws.rs#javax.ws.rs-api;2.1.1!javax.ws.rs-api.${packaging.type}
```

One way to solve this is explicitly adding that dependency:

```
"javax.ws.rs" % "javax.ws.rs-api" % "2.1.1" artifacts Artifact("javax.ws.rs-api", "jar", "jar"),
```

However, this problem does not occur in _every_ use of kafka4s with sbt. We need to figure out the root cause of this problem, and either try to eliminate it completely, or at least document how to avoid it.

**Comment by amohrland** [comment]
@rubbish has discovered why this sometimes crops up in projects using kafka4s:
> I found the little bugger... So in sbt 1.3, they changed to using coursier by default for dep resolution. And when they did, they did run into this bug, however, it required an upstream fix in coursier: sbt/sbt#4682. But this project still depended on the old sbt-coursier plugin, which still had the bug. With that old plugin, this project wouldn't using the builtin resolution and thus ran into the old bug. So I just removed that plugin and it worked perfectly without any other changes.

So, using sbt 1.3+ and removing uses of `sbt-coursier` should fix the issue.
