### ISSUE TITLE
is alterConsumerGroupOffsets supported somehow by the api at this point ?

### ISSUE THREAD

**Issue by okouyad** [Banno/kafka4s#676]
I could not find a function that provide for the functionality ?

**Comment by Kazark** [comment]
Is this a new method on the Java consumer? I'm not aware of it being supported, but I can't say I have the API memorized. PRs are welcome though.

**Comment by okouyad** [comment]
Thanks for the answer.

**Comment by okouyad** [comment]
Unofrtunately i must admit, currently not in a position to  make  open source contrib :(  !! I would love to tho. Sorry about that. Let's see how next year unnfold, if we can save  our company  project first :)
